version: "3.9"

services:

#  server:
#    restart: "unless-stopped"
#    build:
#      context: ./server
#    volumes:
#      - ./config.yml/app/config.yml
#    ports:
#      - "127.0.0.1:5000:5000"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]

  whisper:
    restart: "unless-stopped"
    build:
      context: ./whisper
      args:
        # В качестве версии можно указать: тег, ветку или коммит
        - WHISPER_VERSION=v1.6.2
    volumes:
      - ./models:/app/models
    ports:
      - "127.0.0.1:9000:9000"
    environment:
       WHISPER_MODEL: base
       # WHISPER_MODEL_QUANTIZATION: q4_0
       # WHISPER_PROCESSORS: 1
       # WHISPER_THREADS: 4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  swagger:
    restart: "unless-stopped"
    image: swaggerapi/swagger-ui:v5.17.14
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./whisper/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
