FROM intelanalytics/ipex-llm-inference-cpp-xpu:2.2.0-SNAPSHOT as builder
WORKDIR /app

# Repo with sources
ARG WHISPER_REPO="https://github.com/ggerganov/whisper.cpp.git"

# It may be name of branch, tag or commit hash
ARG WHISPER_VERSION="master"

# Install basic dependencies
RUN set -xe \
 && apt update -q \
 && apt install -fyqq wget ffmpeg git make cmake vim g++ \
 && apt clean

# Clone whisper.cpp repo
RUN git clone --branch "$WHISPER_VERSION" --depth 1 "$WHISPER_REPO"

# Build whisper.cpp with MKL support
WORKDIR /app/whisper.cpp
RUN set -xe  \
 && cmake -B build -DWHISPER_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx \
 && cmake --build build --config Release


FROM intelanalytics/ipex-llm-inference-cpp-xpu:2.2.0-SNAPSHOT
WORKDIR /app

# Install basic dependencies
RUN set -xe \
 && apt update -q \
 && apt install -fyqq wget ffmpeg \
 && apt clean

# Create folders
RUN set -xe \
 && mkdir -pv /app/models /app/audios

# Copy compiled tools
COPY --from=builder /app/whisper.cpp/models/download-ggml-model.sh .
COPY --from=builder /app/whisper.cpp/build/src/*.so /usr/lib/x86_64-linux-gnu
COPY --from=builder /app/whisper.cpp/build/src/*.so.* /usr/lib/x86_64-linux-gnu
COPY --from=builder /app/whisper.cpp/build/ggml/src/*.so /usr/lib/x86_64-linux-gnu
COPY --from=builder /app/whisper.cpp/build/bin/whisper-server .
COPY --from=builder /app/whisper.cpp/build/bin/whisper-cli .
COPY --from=builder /app/whisper.cpp/build/bin/quantize .

# Initialize entrypoint
ADD entrypoint.sh .
ENTRYPOINT ["/app/entrypoint.sh"]
