openapi: 3.0.0

info:
  description: Whisper.cpp HTTP transcription server with OAI-like API in Docker.
  title: Whisper.cpp Service
  version: v1.6.2

servers:
  - description: Instance of Whisper.cpp server
    url: http://localhost:9000

paths:
  /inference:
    post:
      tags: [ Audio ]
      summary: Transcribe audio file
      description: Uploads an audio file and returns the transcription.
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                debug_mode:
                  description: Enable debug mode
                  example: false
                  type: boolean
                  default: ''
                diarize:
                  description: Stereo audio diarization
                  example: false
                  type: boolean
                  default: ''
                file:
                  description: Audio file to be transcribed
                  format: binary
                  type: string
                language:
                  description: Spoken language ('auto' for auto-detect)
                  example: en
                  type: string
                  default: ''
                prompt:
                  description: Initial prompt
                  example: ''
                  type: string
                response_format:
                  description: Format of the response
                  enum:
                    - verbose_json
                    - json
                    - text
                    - srt
                    - vtt
                  example: json
                  type: string
                temperature:
                  description: Temperature setting for the transcription
                  example: 0.0
                  type: number
                tinydiarize:
                  description: Enable tinydiarize (requires a tdrz model)
                  example: false
                  type: boolean
              required: [ file ]
              type: object
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/plain:
              schema:
                type: string
        400:
          description: Bad Request
        500:
          description: Internal Server Error

  /load:
    post:
      tags: [ Models ]
      summary: Load model
      description: Change loaded model
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                model:
                  description: 'Load '
                  example: /app/models/ggml-base.en.bin
                  type: string
              required: [ model ]
              type: object
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  transcription:
                    description: Transcribed text
                    type: string
                type: object
          description: OK
        400:
          description: Bad Request
        500:
          description: Internal Server Error
